version: '3.8'

services:
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    hostname: ollama
    volumes:
      - ollama_data:/root/.ollama
      - ./start.sh:/start.sh:ro,z
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.1:8b}
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - opencode-network
    entrypoint: /bin/bash
    command: ["/start.sh"]

  opencode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opencode
    hostname: opencode
    volumes:
      - ./workspace:/workspace:z
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - opencode-network
    stdin_open: true
    tty: true
    working_dir: /workspace
    command: ["opencode"]

volumes:
  ollama_data:
    driver: local

networks:
  opencode-network:
    driver: bridge