version: '3.8'

services:
  gemini:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemini-cli
    hostname: gemini
    volumes:
      - ./workspace:/workspace:z
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    stdin_open: true
    tty: true
    working_dir: /workspace