services:
  # OpenTelemetry Collector for telemetry collection
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml
      - ./telemetry-data:/telemetry
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver

  # Claude Code container
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-code
    environment:
      # Enable telemetry collection
      - CLAUDE_CODE_ENABLE_TELEMETRY=1
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      
      # Configure OpenTelemetry exporters
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      
      # Set shorter intervals for debugging
      - OTEL_METRIC_EXPORT_INTERVAL=10000
      - OTEL_LOGS_EXPORT_INTERVAL=5000
      
      # User info for tracking - MUST be provided by user
      - USER_NAME=${USER_NAME}
      - USER_EMAIL=${USER_EMAIL}
    volumes:
      - ./workspace:/home/claude-user/workspace
      - ./telemetry-data:/telemetry
    depends_on:
      - otel-collector
    stdin_open: true
    tty: true
