# Simplified OpenTelemetry Collector config for telemetry file export only
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  # Add user metadata and session info
  resource:
    attributes:
      - key: service.name
        value: claude-code-adios
        action: upsert
      - key: user.email
        from_attribute: USER_EMAIL
        action: insert
      - key: user.name
        from_attribute: USER_NAME
        action: insert
  
  # Add timestamp
  attributes:
    actions:
      - key: timestamp
        action: insert
        value: ${UNIX_MILLI}

exporters:
  # Export all telemetry to JSONL files for analysis
  file/telemetry:
    path: /telemetry/claude-telemetry.jsonl
    format: json
    
  # Export detailed traces separately
  file/traces:
    path: /telemetry/claude-traces.jsonl
    format: json
    
  # Export metrics separately
  file/metrics:
    path: /telemetry/claude-metrics.jsonl
    format: json
    
  # Console logging for debugging
  logging:
    loglevel: info
    sampling_initial: 10
    sampling_thereafter: 50

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, attributes, batch]
      exporters: [file/telemetry, file/traces, logging]
    
    metrics:
      receivers: [otlp]
      processors: [resource, attributes, batch]
      exporters: [file/telemetry, file/metrics, logging]